name: rocco the readme racoon
author: petabite
description: rocco keeps your github profile readme up to date.
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate README
      shell: bash
      run: |
        echo "Generating README for ${USERNAME}..."
        curl -o README.md "https://rocco.isupinthe.cloud/api/readme/${USERNAME}"
        echo "Done!"
      env:
        USERNAME: ${{ github.repository_owner	}}

    - name: Push README
      shell: bash
      run: |
        git config user.name "rocco the readme racoon"
        git config user.email "rocco@isupinthe.cloud"
        git add README.md
        git commit -m "update readme"
        git push
